# Generated by Django 5.0.7 on 2024-08-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_customer_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.CharField(choices=[('regular', 'Обычный покупатель'), ('vip', 'VIP покупатель')], default='regular', max_length=10),
        ),
    ]
