# Generated by Django 5.0.7 on 2024-08-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_customer_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
