# Generated by Django 5.0.7 on 2024-08-29 17:30

import review.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[review.models.validate_rating], verbose_name='рейтинг'),
        ),
    ]
