# Generated by Django 5.0.7 on 2024-08-14 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 8, 14, 11, 48, 34, 70957, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
