# Generated by Django 5.0.7 on 2024-08-14 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_app', '0003_alter_author_bio_alter_author_name_and_more'),
        ('orders', '0004_cart_created_cart_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена за товар')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.cart', verbose_name='Корзина')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_in_cart', to='book_shop_app.book', verbose_name='Товар')),
            ],
        ),
    ]
