# Generated by Django 5.0.7 on 2024-08-22 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_itemincart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_order_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tel', models.CharField(max_length=12, verbose_name='Телефон')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='orders.cart')),
            ],
        ),
    ]
