# Generated by Django 5.0.7 on 2024-08-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordergoods_address_alter_ordergoods_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='address',
            field=models.TextField(max_length=300, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='total_order_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Стоимость заказа'),
        ),
    ]
