# Generated by Django 5.0.7 on 2024-09-02 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_ordergoods_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemincart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
