# Generated by Django 5.0.7 on 2024-09-02 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_itemincart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='item_in_cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_in_cart', to='orders.itemincart'),
        ),
    ]
