# Generated by Django 5.0.7 on 2024-09-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_ordergoods_item_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergoods',
            name='item_in_cart',
        ),
    ]
