# Generated by Django 5.0.7 on 2024-09-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_ordergoods_user_orderstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergoods',
            name='user',
        ),
    ]
