# Generated by Django 5.0.7 on 2024-09-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_ordergoods_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='order',
            new_name='ordergoods',
        ),
    ]
