# Generated by Django 5.0.7 on 2024-09-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_ordergoods_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('Ожидает обработки', 'Ожидает обработки'), ('Отправлен', 'Отправлен'), ('Доставлен', 'Доставлен'), ('Отменен', 'Отменен')], max_length=20),
        ),
    ]
