# Generated by Django 5.0.7 on 2024-09-04 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_ordergoods_user_alter_orderstatus_ordergoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='status_order',
            field=models.CharField(choices=[('ожидает обработки', 'ожидает обработки'), ('отправлен', 'отправлен'), ('доставлен', 'доставлен'), ('получен покупателем', 'получен покупателем'), ('отменен', 'отменен')], default='ожидает обработки', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.ordergoods'),
        ),
    ]
