# Generated by Django 5.0.7 on 2024-09-04 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_ordergoods_status_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='ordergoods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='orders.ordergoods', verbose_name='Заказ покупателя'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('ожидает обработки', 'ожидает обработки'), ('отправлен', 'отправлен'), ('доставлен', 'доставлен'), ('получен покупателем', 'получен покупателем'), ('отменен', 'отменен')], max_length=20, verbose_name='Статус'),
        ),
    ]
