# Generated by Django 5.0.7 on 2024-09-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_ordergoods_user_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergoods',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='ordergoods',
            name='user_2',
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='user',
            field=models.CharField(default='', max_length=20, verbose_name='Покупатель'),
        ),
    ]
