# Generated by Django 5.0.7 on 2024-09-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_remove_ordergoods_user_1_remove_ordergoods_user_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('ожидает обработки', 'ожидает обработки'), ('отправлен', 'отправлен'), ('доставлен', 'доставлен'), ('товар получен', 'товар получен'), ('отменен', 'отменен')], default='ожидает обработки', max_length=20, verbose_name='Статус'),
        ),
    ]
