# Generated by Django 5.0.7 on 2024-07-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cover',
            field=models.ImageField(upload_to='item_covers/%Y/%m/%d', verbose_name='Item cover'),
        ),
    ]
