# Generated by Django 5.0.7 on 2024-08-12 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_app', '0002_author_book_firstpage_genre_publisher_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Краткая биография автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='age_restrictions',
            field=models.CharField(blank=True, max_length=50, verbose_name='Возрастные ограничения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='book_shop_app.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='binding',
            field=models.CharField(max_length=50, verbose_name='Переплет'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='book_covers/%Y/%m/%d', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог'),
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(max_length=50, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='book_shop_app.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступен для заказа'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, verbose_name='Международный стандартный книжный номер (ISBN)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения карточки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='book_shop_app.publisher', verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество книг в наличии'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='book_shop_app.series', verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.FloatField(verbose_name='Вес книги'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес издательства'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название издательства'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(blank=True, verbose_name='Вебсайт издательства'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Серия'),
        ),
    ]
