# Generated by Django 5.0.7 on 2024-07-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_app', '0002_author_book_genre_publisher_series_delete_directory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
    ]
