# Generated by Django 5.0.7 on 2024-08-22 08:38

import book_shop_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_app', '0003_alter_author_bio_alter_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='book_covers/%Y/%m/%d', validators=[book_shop_app.models.validate_image_size], verbose_name='Обложка'),
        ),
    ]
