# Generated by Django 5.0.7 on 2024-08-29 17:30

import book_shop_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop_app', '0004_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0.0, validators=[book_shop_app.models.validate_rating], verbose_name='Рейтинг книги'),
        ),
    ]
